FROM maven:3.9.2-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/order-lambda-1.0-SNAPSHOT.jar order-lambda.jar

CMD ["java", "-jar", "order-lambda.jar"]
